Vagrant.configure("2") do |c|
  c.berkshelf.enabled = false if Vagrant.has_plugin?("vagrant-berkshelf")
  c.vm.box = "bento/centos-8"
  c.vm.hostname = "default-centos-8.vagrantup.com"
  c.vm.synced_folder ".", "/vagrant", disabled: true
  c.vm.synced_folder "/root/.kitchen/cache", "/tmp/omnibus/cache", create: true
  c.vm.provider :virtualbox do |p|
    p.name = "kitchen-sgl-base-cookbook-default-centos-8-5e107926-8aa1-4a35-94c7-3fb6b69641f9"
    p.customize ["modifyvm", :id, "--audio", "none"]
  end
end
